<?php
declare(strict_types=1);
header('Cache-Control: no-store'); header('X-Content-Type-Options: nosniff'); header('Referrer-Policy: no-referrer');
header("Content-Security-Policy: default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; media-src 'self' blob:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'");
if (($_SERVER['REQUEST_METHOD']??'')!=='GET') { http_response_code(405); exit; }
if (($_SERVER['HTTPS']??'')!=='on') { http_response_code(426); echo 'This local device viewer requires HTTPS.'; exit; }
?>
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Local site announcements</title>
<style>body{font:18px system-ui,sans-serif;background:#101b2b;color:#edf3fc;margin:0;padding:28px;max-width:1100px}h1{font-size:28px}label{display:block;margin:14px 0}input{font:inherit;background:#fff;color:#101b2b;border:1px solid #b8c7da;border-radius:5px;padding:9px;max-width:100%;box-sizing:border-box}button{font:inherit;border:0;border-radius:5px;background:#6ed9ca;color:#071c20;padding:11px 20px;margin-right:10px;cursor:pointer}button:disabled{opacity:.6}#status{min-height:28px;color:#bcd1ed}.event{background:#1c304d;border-left:6px solid #6ed9ca;border-radius:6px;padding:24px;margin:20px 0}.event h2{margin-top:0}.event p{font-size:27px;white-space:pre-wrap;overflow-wrap:anywhere}.meta{font-size:14px;color:#bcd1ed}.fields{display:flex;flex-wrap:wrap;gap:16px}.fields label{flex:1;min-width:220px}.fields input{display:block;width:100%}</style>
<body><h1>Local site announcements</h1><p>This device receives its site's approved local display and cached audio jobs. Each job expires automatically. Application receipts do not indicate human acknowledgment.</p>
<form id="connect"><div class="fields"><label>Owned device ID<input id="device" maxlength="96" autocomplete="off" required></label><label>Local device bearer token<input id="token" type="password" minlength="32" maxlength="256" autocomplete="off" required></label></div><label><input id="sound" type="checkbox"> Play approved cached audio on this device</label><button type="submit" id="start">Connect local device</button><button type="button" id="stop" disabled>Disconnect</button></form>
<p id="status" role="status">Enter the device credentials assigned by your local administrator.</p><main id="events" aria-live="polite"></main>
<script>
(function(){'use strict';
const form=document.getElementById('connect'),status=document.getElementById('status'),events=document.getElementById('events');
let running=false,device='',token='',sound=false,timer=null,ledger={},key='',audio=null,audioExpires=0,generation=0;
function persist(){localStorage.setItem(key,JSON.stringify(ledger));}
function load(){const raw=localStorage.getItem(key);ledger=raw?JSON.parse(raw):{};if(!ledger||Array.isArray(ledger)||typeof ledger!=='object'||Object.keys(ledger).length>1000)throw new Error('Local delivery history is invalid; administrator review is required.');for(const [id,row]of Object.entries(ledger)){if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,95}$/.test(id)||!row||!Number.isInteger(row.expires_at)||!['uncertain','receipted'].includes(row.state))throw new Error('Local delivery history is invalid; administrator review is required.');}}
function prune(){const now=Math.floor(Date.now()/1000);for(const [id,row]of Object.entries(ledger))if(now>=row.expires_at)delete ledger[id];persist();for(const card of events.children)if(now>=Number(card.dataset.expires)){card.remove();}}
function endpoint(action,extra={}){const u=new URL('edge.php',location.href);u.searchParams.set('device_id',device);u.searchParams.set('action',action);for(const [k,v]of Object.entries(extra))u.searchParams.set(k,v);return u;}
async function request(action,body,extra={}){const response=await fetch(endpoint(action,extra),{method:body?'POST':'GET',credentials:'omit',cache:'no-store',redirect:'error',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error('The local device credential, event, or site service is unavailable.');if(action==='media'){const blob=await response.blob();if(blob.size>2097152||!response.headers.get('Content-Type')?.startsWith('audio/wav'))throw new Error('Invalid bounded cached audio response.');return blob;}return response.json();}
async function deliver(event,active){const now=Math.floor(Date.now()/1000);if(!event||typeof event.id!=='string'||!/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,95}$/.test(event.id)||!Number.isInteger(event.expires_at)||event.expires_at<=now||event.expires_at>now+900||typeof event.message!=='string'||typeof event.title!=='string'||!Array.isArray(event.channels))throw new Error('The local site supplied an invalid bounded event.');if(ledger[event.id])return;if(Object.keys(ledger).length>=1000)throw new Error('Local delivery history reached its bound; dispatch is paused.');ledger[event.id]={expires_at:event.expires_at,state:'uncertain'};persist();
 const card=document.createElement('article');card.className='event';card.dataset.expires=event.expires_at;const title=document.createElement('h2'),message=document.createElement('p'),meta=document.createElement('div');title.textContent=event.title;message.textContent=event.message;meta.className='meta';meta.textContent='Expires '+new Date(event.expires_at*1000).toLocaleTimeString();card.append(title,message,meta);events.prepend(card);
 let kind='displayed';if(sound&&event.channels.includes('local_audio')&&event.audio_asset_id){const blob=await request('media',null,{event_id:event.id,asset_id:event.audio_asset_id});if(!running||generation!==active||Math.floor(Date.now()/1000)>=event.expires_at)return;const url=URL.createObjectURL(blob);audio=new Audio(url);audioExpires=event.expires_at;try{await new Promise((resolve,reject)=>{audio.onended=resolve;audio.onpause=()=>{if(audio&&!audio.ended)reject(new Error('Cached audio stopped or expired; this event will not automatically replay.'));};audio.onerror=()=>reject(new Error('Cached audio playback was interrupted; this event will not automatically replay.'));audio.play().catch(reject);});kind='audio_played';}finally{URL.revokeObjectURL(url);audio=null;audioExpires=0;}}
 if(!running||generation!==active||Math.floor(Date.now()/1000)>=event.expires_at)return;await request('receipt',{id:event.id,kind});if(!running||generation!==active)return;ledger[event.id].state='receipted';persist();}
async function poll(active){if(!running||generation!==active)return;try{prune();const result=await request('poll');if(!Array.isArray(result.events)||result.events.length>50)throw new Error('Invalid local event list.');for(const event of result.events){if(!running||generation!==active)break;await deliver(event,active);}if(running&&generation===active)status.textContent='Connected to the local site. Waiting for unexpired owned-device jobs.';}catch(error){if(running&&generation===active)status.textContent=error.message+' Completed or uncertain events will not automatically replay.';}finally{if(running&&generation===active)timer=setTimeout(()=>poll(active),2000);}}
form.onsubmit=event=>{event.preventDefault();if(running)return;try{device=document.getElementById('device').value.trim();token=document.getElementById('token').value;sound=document.getElementById('sound').checked;if(!/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,95}$/.test(device)||!/^[A-Za-z0-9._~-]{32,256}$/.test(token))throw new Error('Enter valid local device credentials.');key='sls-edge-history-v1:'+device;load();prune();running=true;generation++;document.getElementById('start').disabled=true;document.getElementById('stop').disabled=false;status.textContent='Connecting to the local site…';poll(generation);}catch(error){status.textContent=error.message;token='';}};
document.getElementById('stop').onclick=()=>{running=false;generation++;clearTimeout(timer);if(audio)audio.pause();token='';document.getElementById('token').value='';document.getElementById('start').disabled=false;document.getElementById('stop').disabled=true;status.textContent='Disconnected. Local delivery history remains preserved.';};
setInterval(()=>{const now=Math.floor(Date.now()/1000);if(audio&&now>=audioExpires)audio.pause();for(const card of events.children)if(now>=Number(card.dataset.expires))card.remove();},1000);
})();
</script></body></html>
