(()=>{'use strict';const root=document.getElementById('enterprise-identity-labs');if(!root)return;const boot=JSON.parse(root.querySelector('[data-identity-bootstrap]').textContent);const find=s=>root.querySelector(s);const status=find('[data-identity-status]');let plan='';
const read=key=>JSON.parse(find('[data-config="'+key+'"]').value);const write=(key,v)=>{find('[data-config="'+key+'"]').value=JSON.stringify(v,null,2);};const randomId=prefix=>{const b=new Uint8Array(12);crypto.getRandomValues(b);return prefix+Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');};
const call=async(action,input)=>{status.textContent='Working…';const body=new URLSearchParams({slsmassnotifyserver_action:'enterprise_labs',slsmassnotifyserver_csrf:boot.csrf,payload:JSON.stringify({action,input})});const r=await fetch(boot.endpoint,{method:'POST',credentials:'same-origin',body,headers:{'Accept':'application/json'}});const data=await r.json();status.textContent=data.message||'Request completed.';status.className=data.success?'alert alert-success':'alert alert-danger';if(!data.success)throw new Error(data.message||'Request failed');return data;};
const run=fn=>async()=>{try{await fn();}catch(e){status.textContent=e.message;status.className='alert alert-danger';}};
root.querySelectorAll('[data-save-config]').forEach(button=>button.addEventListener('click',run(async()=>{const key=button.dataset.saveConfig;const action={identity:'identity_save',directory:'directory_save',subscriber:'subscriber_save'}[key];const config=read(key);if(key==='identity'&&config.enabled){if(!window.SlsLabsSafety)throw Error('Open Enterprise Labs to review the enterprise login warning.');if(!await window.SlsLabsSafety.acknowledge())return;}const data=await call(action,{config,revision:boot.revisions[key]});write(key,data.config);boot.revisions[key]=data.revision;plan='';find('[data-apply-directory]').disabled=true;})));
find('[data-add-provider]').addEventListener('click',run(()=>{const c=read('identity'),vendor=find('[data-provider-vendor]').value,protocol=find('[data-provider-protocol]').value;const p={id:randomId('idp_'),vendor,protocol,name:{entra:'Entra ID',okta:'Okta',google:'Google Workspace',keycloak:'Keycloak',onelogin:'OneLogin'}[vendor],enabled:false,issuer:'',callback_url:''};
if(protocol==='oidc'){Object.assign(p,{discovery_url:'',client_id:'',client_secret:'',token_auth:vendor==='onelogin'?'none':'client_secret_basic',endpoint_hosts:[],hosted_domain:''});if(vendor==='google'){p.issuer='https://accounts.google.com';p.discovery_url=p.issuer+'/.well-known/openid-configuration';p.endpoint_hosts=['accounts.google.com','oauth2.googleapis.com','www.googleapis.com'];}}
else Object.assign(p,{idp_sso_url:'',idp_signing_certificates:[],sp_entity_id:'',sp_certificate:'',sp_private_key:'',nameid_format:'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'});c.providers.push(p);write('identity',c);status.textContent='Provider added disabled. Fill its registered issuer, callback, credentials and certificate fields before saving.';}));
find('[data-add-source]').addEventListener('click',run(()=>{const c=read('directory'),type=find('[data-source-type]').value;const s={id:randomId('dir_'),name:'New '+type+' source',type,enabled:false,template_ids:[],sync_subscribers:false,records:[]};if(type==='ldap')Object.assign(s,{ldap_url:'',ldap_starttls:true,ldap_bind_dn:'',ldap_password:'',ldap_base_dn:'',ldap_filter:'(objectClass=person)',ldap_attributes:{external_id:'entryUUID',name:'displayName',email:'mail',location:'l',desktop_username:'uid',active:''},ldap_inactive_values:['false','0']});if(type==='scim')Object.assign(s,{scim_base_url:'',scim_token:''});c.sources.push(s);write('directory',c);status.textContent='Source added disabled. Complete its template assignment and connector fields before saving.';}));
find('[data-preview-directory]').addEventListener('click',run(async()=>{const input={source_id:find('[data-preview-source]').value.trim()};const file=find('[data-csv-file]').files[0];if(file){if(file.size>524288)throw new Error('CSV exceeds 512 KiB.');input.csv=await file.text();}const data=await call('directory_preview',input);plan=data.plan_id;find('[data-directory-diff]').textContent=JSON.stringify(data.plan,null,2);find('[data-apply-directory]').disabled=false;}));
find('[data-preview-deprovision]').addEventListener('click',run(async()=>{const data=await call('directory_preview',{source_id:find('[data-preview-source]').value.trim(),deprovision_all:true});plan=data.plan_id;find('[data-directory-diff]').textContent=JSON.stringify(data.plan,null,2);find('[data-apply-directory]').disabled=false;}));
find('[data-apply-directory]').addEventListener('click',run(async()=>{if(!plan)throw new Error('Run a dry run first.');await call('directory_apply',{plan_id:plan});plan='';find('[data-apply-directory]').disabled=true;location.reload();}));
find('[data-add-subscriber]').addEventListener('click',run(()=>{const c=read('subscriber');c.people.push({id:randomId('sub_'),person_id:'',name:'',email:'',enabled:false});write('subscriber',c);status.textContent='Person added disabled. Fill an exact incident roster person ID, name and email before saving. Registration time and version are assigned by the server.';}));
find('[data-invite-subscriber-button]').addEventListener('click',run(()=>call('subscriber_invite',{subscriber_id:find('[data-invite-subscriber]').value.trim(),incident_id:find('[data-invite-incident]').value.trim()})));
find('[data-revoke-subscriber]').addEventListener('click',run(async()=>{const data=await call('subscriber_revoke',{subscriber_id:find('[data-invite-subscriber]').value.trim()});write('subscriber',data.config);boot.revisions.subscriber=data.revision;}));
})();
