<?php
$integrationsRevision=substr(hash('sha256',hash_file('sha256',__DIR__.'/integrations.js').hash_file('sha256',__DIR__.'/integrations.css')),0,16);
?>
<link rel="stylesheet" href="modules/slsmassnotifyserver/views/integrations.css?v=<?php echo $integrationsRevision; ?>">
<section id="sls-integrations" aria-labelledby="sls-integrations-title">
<div class="sls-integration-heading"><div><h2 id="sls-integrations-title"><i class="fa fa-plug" aria-hidden="true"></i> Devices and response providers <?php include __DIR__.'/labs.php'; ?></h2><p class="text-muted">Connect saved speakers, enrolled sensors, incident response channels and authorized external providers.</p></div><span class="sls-integration-chip"><i class="fa fa-flask" aria-hidden="true"></i> Acceptance pending</span></div>
<p class="sls-integration-notice">These adapters have isolated protocol tests. Your hardware, provider accounts and physical results still require acceptance testing. Every integration starts disabled.</p>
<div id="sls-integration-status" role="status" tabindex="-1" hidden></div>
<form id="sls-integration-form">
<label class="sls-integration-switch"><input type="checkbox" data-setting="enabled"> Enable device and provider integrations</label>
<div class="sls-integration-grid">
<section class="sls-integration-card"><h3><i class="fa fa-volume-up" aria-hidden="true"></i> SIP speakers</h3><p>Five representative brands use existing PBX extensions and the normal queued audio delivery path. SIP acceptance confirms neither audibility nor screen content.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="speakers.enabled"> Enable saved speaker profiles</label><div id="sls-integration-speakers"></div><button type="button" class="btn btn-default btn-sm" data-add="speaker"><i class="fa fa-plus" aria-hidden="true"></i> Add speaker</button><p class="help-block">Register and configure auto-answer on each device using its vendor instructions. Axis telemetry reads the last speaker test report without playing test tones.</p></section>
<section class="sls-integration-card"><h3><i class="fa fa-door-open" aria-hidden="true"></i> Access control</h3><p>Axis VAPIX controllers expose only saved door tokens and their selected read, lock and unlock permissions.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="access_control.enabled"> Enable controller integration</label><div class="sls-integration-fields">
<label>Controller HTTPS origin<input class="form-control" data-setting="access_control.origin" placeholder="https://controller.example.org" type="url"></label><label>Pinned private IPv4<input class="form-control" data-setting="access_control.pinned_ipv4" placeholder="192.168.20.10"></label><label>Controller user<input class="form-control" data-setting="access_control.username" autocomplete="off"></label><label>Controller password<input class="form-control" data-setting="access_control.password" type="password" autocomplete="new-password" placeholder="Blank keeps saved credential"><span><input type="checkbox" data-clear="access_control.password"> Clear saved password</span></label></div><div id="sls-integration-doors"></div><button type="button" class="btn btn-default btn-sm" data-add="door"><i class="fa fa-plus" aria-hidden="true"></i> Add permitted door</button><p class="help-block">Use a controller account with matching device permissions. Lock and unlock require the Enterprise Labs danger acknowledgement. Reading reported state does not prove the physical lock changed.</p></section>
<section class="sls-integration-card"><h3><i class="fa fa-video-camera" aria-hidden="true"></i> Incident meetings</h3><p>Create an incident coordination meeting using an authorized OAuth account. Meeting creation does not send invitations.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="meetings.enabled"> Enable meeting creation</label><div class="sls-integration-fields"><label>Provider<select class="form-control" data-setting="meetings.provider"><option value="zoom">Zoom</option><option value="google_meet">Google Meet</option><option value="webex">Webex</option></select></label><label>Zoom host user<input class="form-control" data-setting="meetings.zoom_user" placeholder="me"></label>
<?php foreach (['zoom'=>'Zoom','google'=>'Google Meet','webex'=>'Webex'] as $key=>$label): ?><label><?php echo $label; ?> OAuth access token<input class="form-control" type="password" data-setting="meetings.<?php echo $key; ?>_access_token" autocomplete="new-password" placeholder="Blank keeps saved credential"><span><input type="checkbox" data-clear="meetings.<?php echo $key; ?>_access_token"> Clear saved token</span></label><?php endforeach; ?></div><p class="help-block">Use an authorized app with meeting creation permission. Renew expired access tokens through your OAuth application. Google Meet creates a restricted space; this adapter does not schedule a Calendar event.</p></section>
<section class="sls-integration-card"><h3><i class="fa fa-reply" aria-hidden="true"></i> Participant SMS and voice replies</h3><p>Bind an incident participant to a saved, consented SMS or voice recipient. Signed SMS replies use a unique incident code. Voice records an explicit keypad acknowledgement after the announcement audio.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="responses.enabled"> Enable explicit participant replies</label><label>Reply validity (seconds)<input class="form-control" type="number" min="60" max="86400" data-setting="responses.ttl_seconds"></label><div id="sls-integration-bindings"></div><button type="button" class="btn btn-default btn-sm" data-add="binding"><i class="fa fa-plus" aria-hidden="true"></i> Bind participant</button><p class="help-block">Twilio and Telnyx signatures, saved provider routing, participant identity and incident code must match. BulkVS inbound replies are unsupported. No reply, SIP answer and carrier delivery remain separate evidence.</p></section>
<section class="sls-integration-card"><h3><i class="fa fa-heartbeat" aria-hidden="true"></i> Physical sensor health</h3><p>Raspberry Pi, ESP32 and Arduino examples use the existing enrolled trigger's HTTPS signature, replay protection and cooldown. Heartbeats report source freshness and never activate an incident.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="sensors.enabled"> Enable enrolled sensor heartbeats</label><label>Heartbeat stale after (seconds)<input class="form-control" type="number" min="30" max="3600" data-setting="sensors.heartbeat_timeout_seconds"></label><div id="sls-integration-sensor-health"></div><p class="help-block">Use approved isolated inputs. These examples do not connect to, modify or supervise a fire panel. A fresh source heartbeat does not establish sensor accuracy.</p><a href="config.php?display=slsmassnotifyserver_automations" class="btn btn-default btn-sm">Manage enrolled triggers</a></section>
<section class="sls-integration-card"><h3><i class="fa fa-bullhorn" aria-hidden="true"></i> CAP and authorized public warning</h3><p>Author and export a bounded CAP 1.2 warning with explicit affected areas, expiry and update/cancel references. Exporting a draft transmits no alert.</p><label class="sls-integration-switch"><input type="checkbox" data-setting="public_warning.enabled"> Enable CAP authoring and export</label><label class="sls-integration-switch"><input type="checkbox" data-setting="public_warning.ipaws_enabled"> Enable authorized IPAWS adapter</label><div class="sls-integration-fields"><label>FEMA-issued CAP service endpoint<input class="form-control" data-setting="public_warning.endpoint" type="url" placeholder="https://…fema.gov/IPAWS_CAPService/IPAWS"></label><label>WSDL postCAP SOAPAction<input class="form-control" data-setting="public_warning.soap_action" autocomplete="off" placeholder="Exact action from issued WSDL"></label><label>Logon user<input class="form-control" data-setting="public_warning.logon_user" autocomplete="off"></label><label>Authorized COG ID<input class="form-control" data-setting="public_warning.cog_id" autocomplete="off"></label></div>
<details><summary>Authority certificate and signing key</summary><div class="sls-integration-fields"><label>X.509 certificate PEM<textarea class="form-control" data-setting="public_warning.certificate_pem" rows="4" autocomplete="off" placeholder="Blank keeps the saved certificate"></textarea><span><input type="checkbox" data-clear="public_warning.certificate_pem"> Clear saved certificate</span></label><label>Private key PEM<textarea class="form-control" data-setting="public_warning.private_key_pem" rows="4" autocomplete="off" placeholder="Blank keeps the saved key"></textarea><span><input type="checkbox" data-clear="public_warning.private_key_pem"> Clear saved key</span></label><label>Private key passphrase<input type="password" class="form-control" data-setting="public_warning.private_key_password" autocomplete="new-password" placeholder="Blank keeps saved credential"><span><input type="checkbox" data-clear="public_warning.private_key_password"> Clear saved passphrase</span></label></div><label><input type="checkbox" data-setting="public_warning.authority_confirmed"> This organization has an authorized COG and the required channel/area permissions</label></details><p class="help-block">IPAWS remains unqualified until the authorized organization verifies its issued WSDL and CDTE workflow. The adapter accepts a matching signed envelope prepared by that authorized integration. FEMA authority, certificates and dissemination confirmation are not supplied by SLS.</p></section>
</div><div class="sls-integration-footer"><button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save integration settings</button><span>Saved configuration does not contact devices or providers.</span></div>
</form>
<div class="sls-integration-grid">
<section class="sls-integration-card"><h3>Coordinate an open incident</h3><p>Use the saved meeting provider. Creating a meeting contacts that provider and adds its join link to the activity record.</p><form id="sls-integration-meeting"><label>Open incident<select id="sls-integration-meeting-incident" class="form-control" required></select></label><div class="sls-integration-fields"><label>Start time<input id="sls-integration-meeting-start" type="datetime-local" class="form-control" required></label><label>Duration (minutes)<input id="sls-integration-meeting-duration" type="number" min="5" max="240" value="30" class="form-control" required></label></div><button type="submit" class="btn btn-primary" data-operation-section="meetings">Create coordination meeting</button></form></section>
<section class="sls-integration-card"><h3>Page saved SIP speakers</h3><p>Uses the existing audio queue and individual PBX admission. Review the usual delivery details for per-extension results.</p><form id="sls-integration-speaker-send"><div id="sls-integration-speaker-selection"></div><label>Announcement title<input id="sls-integration-speaker-title" value="Speaker drill" maxlength="80" class="form-control" required></label><label>Spoken message<textarea id="sls-integration-speaker-message" maxlength="500" rows="3" class="form-control" required></textarea></label><label><input id="sls-integration-speaker-test" type="checkbox" checked> This is a drill</label><button type="submit" class="btn btn-primary" data-operation-section="speakers">Queue speaker announcement</button></form></section>
<section class="sls-integration-card"><h3>Saved door operations</h3><p>Only saved permissions are available. Unlock keeps the door unlocked until the controller receives another valid command. Read state before and after an authorized operation.</p><div id="sls-integration-door-actions"></div></section>
<section class="sls-integration-card"><h3>Author and export a CAP warning</h3><p>Review the structured draft and export it before preparing an authorized IPAWS submission.</p><form id="sls-integration-cap"><div class="sls-integration-fields"><label>Alert identifier<input name="identifier" class="form-control" maxlength="128" required></label><label>Sender identity<input name="sender" class="form-control" maxlength="128" required></label><label>Sent time<input name="sent" type="datetime-local" class="form-control" required></label><label>Expires at<input name="expires" type="datetime-local" class="form-control" required></label><label>Status<select name="status" class="form-control"><option>Test</option><option>Exercise</option><option>Actual</option></select></label><label>Message type<select name="msg_type" class="form-control"><option>Alert</option><option>Update</option><option>Cancel</option></select></label><label>Event<input name="event" class="form-control" maxlength="100" required></label><label>Headline<input name="headline" class="form-control" maxlength="160" required></label></div><label>Description<textarea name="description" class="form-control" maxlength="4000" rows="3" required></textarea></label><label>Instruction<textarea name="instruction" class="form-control" maxlength="2000" rows="2"></textarea></label><label>Affected area<input name="area_description" class="form-control" maxlength="1000" required></label><label>Closed polygon (latitude,longitude pairs)<textarea name="polygon" class="form-control" rows="2" placeholder="40,-90 41,-90 40,-89 40,-90"></textarea></label><label>SAME area codes (six digits, separated by spaces)<input name="geocodes" class="form-control"></label><details><summary>Update and cancellation references</summary><label>Referenced original identifier<input name="reference_identifier" class="form-control" maxlength="128"></label><label>Original sent time<input name="reference_sent" type="datetime-local" class="form-control"></label></details><label><input name="ipaws_profile" type="checkbox"> Include the IPAWS profile code</label><button type="submit" class="btn btn-default" data-operation-section="public_warning">Review and export CAP XML</button></form><pre id="sls-integration-cap-preview" hidden></pre><details><summary>Authorized IPAWS submission</summary><p>Paste the matching signed postCAP SOAP envelope generated from your authority-issued WSDL. The saved authority and both signatures must match the exported draft.</p><label>Signed envelope<textarea id="sls-integration-ipaws-envelope" class="form-control" rows="5" maxlength="131072"></textarea></label><button id="sls-integration-ipaws-send" type="button" class="btn btn-danger" disabled>Submit reviewed warning to IPAWS</button></details></section>
</div><section class="sls-integration-card"><h3><i class="fa fa-history" aria-hidden="true"></i> Recent provider activity</h3><p>Claims and uncertain outcomes are preserved. Repeating a request identifier does not repeat a provider operation.</p><div id="sls-integration-history"></div></section>
<script type="application/json" id="sls-integration-data"><?php echo json_encode(['state'=>$state,'csrf'=>$csrf_token??''],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR); ?></script>
<script src="modules/slsmassnotifyserver/views/integrations.js?v=<?php echo $integrationsRevision; ?>" defer></script>
</section>
