<?php $e=static fn($v): string=>htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>
<style><?php readfile(__DIR__.'/operators.css'); ?></style>
<style>.ops-floorplan{position:relative;max-width:100%;margin:1rem 0}.ops-floorplan img{display:block;width:100%;height:auto}.ops-floorplan-marker{position:absolute;transform:translate(-50%,-50%);border:2px solid #fff;border-radius:50%;width:1.7rem;height:1.7rem;box-shadow:0 0 0 1px #222;background:#555}.ops-floorplan-marker[data-status="needs_assistance"]{background:#b42318}.ops-floorplan-marker[data-status="missing"]{background:#a15c00}.ops-floorplan-marker[data-status="responded"]{background:#175cd3}.ops-review-copy{white-space:pre-wrap}.ops-drill-objective{display:block;margin:.5rem 0}</style>
<div class="container-fluid"><div class="display full-border"><div class="fpbx-container"><div id="sls-operations" class="sls-ops">
<div class="ops-heading"><div><h2><i class="fa fa-th-large" aria-hidden="true"></i> Operations <?php include __DIR__.'/labs.php'; ?></h2><p class="ops-muted">Your authorized alerts, schedules and incident roster.</p></div><span class="ops-badge"><?php echo $e($state['principal']['name'] ?: $state['principal']['username']); ?> · <?php echo $e($state['principal']['operator_role']); ?></span></div>
<div class="ops-notice"><i class="fa fa-shield" aria-hidden="true"></i> Recipients and roster entries follow your current site and audience assignments. Desktop receipts confirm software delivery; human responses are recorded separately.</div>
<?php if ($state['can_send'] || $state['can_schedule']): ?>
<form id="ops-compose" class="ops-card"><h3><i class="fa fa-bullhorn" aria-hidden="true"></i> <?php echo $state['can_send'] ? 'New announcement' : 'Schedule an announcement'; ?></h3>
<?php if ($state['can_send'] && $state['can_schedule']): ?><label class="ops-field">Delivery timing<select name="submission_mode"><option value="send">Send now</option><option value="schedule">Schedule for later</option></select></label><?php endif; ?>
<div class="ops-grid"><label class="ops-field">Title<input name="title" maxlength="80" required autocomplete="off"></label><label class="ops-field">Audio<select name="audio_mode"><option value="none">Text only</option><option value="tts">Speech</option><option value="tones">Tones only</option><option value="tones_tts" selected>Tones and speech</option></select></label></div>
<label class="ops-field">Message<textarea name="message" maxlength="500" required></textarea><small class="ops-muted">Up to 500 characters. Speech that exceeds the configured duration is rejected with an error.</small></label>
<div class="ops-grid"><label class="ops-field">Phone display<select name="style"><option value="standard">Text popup</option><option value="colored">Colored image</option></select></label><label class="ops-field" id="ops-color" hidden>Image background<input type="color" name="background_color" value="#1f2937"></label></div>
<div class="ops-grid" id="ops-tones" hidden><?php foreach (['opening_tone'=>'Opening tone', 'closing_tone'=>'Closing tone'] as $key=>$label): ?><label class="ops-field"><?php echo $e($label); ?><select name="<?php echo $e($key); ?>"><option value="">None</option><?php foreach ($state['tones'] as $tone): ?><option value="<?php echo $e($tone); ?>"><?php echo $e($tone); ?></option><?php endforeach; ?><?php $available_system_sounds = $state['recordings'] ?? []; include __DIR__.'/system_recording_options.php'; ?></select></label><?php endforeach; ?></div>
<h3><i class="fa fa-users" aria-hidden="true"></i> Select recipients</h3><div class="ops-grid">
<?php foreach (['extensions'=>'Phone extensions', 'desktop_clients'=>'Desktop applications', 'voice_recipient_ids'=>'External phone calls', 'email_recipient_ids'=>'Email', 'sms_recipient_ids'=>'SMS', 'webhook_ids'=>'Webhooks'] as $key=>$label): if (!$state['choices'][$key]) { continue; } ?>
<details><summary><?php echo $e($label); ?> <span class="ops-muted">· <?php echo count($state['choices'][$key]); ?> available</span></summary><div class="ops-scroll"><?php foreach ($state['choices'][$key] as $row): ?><label class="ops-check"><input type="checkbox" data-channel="<?php echo $e($key); ?>" value="<?php echo $e($row['id']); ?>"><span><?php echo $e($row['name']); ?></span></label><?php endforeach; ?></div></details>
<?php endforeach; ?></div>
<?php if ($state['can_schedule']): ?><div class="ops-grid" id="ops-schedule-fields"><label class="ops-field">Schedule name<input name="schedule_name" maxlength="80" required></label><label class="ops-field">Run at · <?php echo $e($state['timezone']); ?><input name="run_at" type="datetime-local" required></label><label class="ops-field">Repeat<select name="recurrence_mode"><option value="none">Once</option><option value="every_7_days">Every 7 days</option><option value="every_14_days">Every 14 days</option></select></label><label class="ops-field">Maximum start delay (minutes)<input name="lateness_minutes" type="number" min="1" max="15" value="15" required></label></div><?php endif; ?>
<div id="ops-delivery-results" class="ops-preview" hidden role="status" aria-live="polite"></div>
<div id="ops-preview" class="ops-preview" hidden></div><div class="ops-actions"><button type="submit" id="ops-review" class="btn btn-default"><i class="fa fa-eye" aria-hidden="true"></i> Review recipients</button><button type="button" id="ops-submit" class="btn btn-primary" disabled><i class="fa <?php echo $state['can_schedule'] ? 'fa-calendar' : 'fa-paper-plane'; ?>" aria-hidden="true"></i> <?php echo $state['can_schedule'] ? 'Save schedule' : 'Send announcement'; ?></button></div><p id="ops-compose-status" class="ops-status" role="status" aria-live="polite"></p>
</form><?php endif; ?>
<?php if ($state['can_send']): ?><div class="ops-card"><h3><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Incident templates</h3><p class="ops-muted">Templates appear only when their audience and any supervisor follow-up fit your current assignments.</p><div class="ops-actions"><?php foreach ($state['templates'] as $template): ?><button type="button" class="btn btn-default" data-template="<?php echo $e($template['id']); ?>"><?php echo $e($template['name']); ?></button><?php endforeach; ?><?php if (!$state['templates']): ?><span class="ops-muted">No authorized templates configured.</span><?php endif; ?></div></div><?php endif; ?>
<?php if ($state['can_schedule']): ?><div class="ops-card"><h3><i class="fa fa-calendar" aria-hidden="true"></i> Your schedules</h3><?php foreach ($state['schedules'] as $schedule): ?><div class="ops-heading"><p><strong><?php echo $e($schedule['name']); ?></strong><br><span class="ops-muted"><?php echo count($schedule['occurrences']); ?> saved occurrence(s) · <?php echo $e($schedule['timezone']); ?> · <?php echo $schedule['enabled'] === '1' ? 'enabled' : 'disabled'; ?></span></p><button type="button" class="btn btn-default btn-sm" data-remove-schedule="<?php echo $e($schedule['id']); ?>"><i class="fa fa-trash" aria-hidden="true"></i> Remove future occurrences</button></div><?php endforeach; ?><?php if (!$state['schedules']): ?><p class="ops-muted">No schedules saved by this account.</p><?php endif; ?></div><?php endif; ?>
<?php $enterprise=$state['enterprise']??['enabled'=>false]; if ($enterprise['enabled']): ?>
<div class="ops-notice"><strong>DO NOT USE ON PRODUCTION SERVERS.</strong> Enterprise operations are Labs features. Approvals, human responses and drill reviews each retain separate evidence.</div>
<?php foreach ($enterprise['warnings']??[] as $warning): ?><p class="ops-notice" role="status"><?php echo $e($warning); ?></p><?php endforeach; ?>
<?php if (!empty($enterprise['approvals'])): ?><div class="ops-card"><h3>Assigned announcement approvals</h3><p class="ops-muted">Review the frozen wording and recipients. Two distinct authorized people must approve every applicable policy before an approved request can be submitted.</p>
<?php foreach ($enterprise['approvals'] as $review): ?><details><summary><?php echo $e($review['title']); ?> <span class="ops-badge"><?php echo $e(str_replace('_',' ',$review['state'])); ?><?php echo $review['is_test']?' · drill':''; ?></span></summary><p class="ops-review-copy"><?php echo $e($review['message']); ?></p><p class="ops-muted">Expires <?php echo $e($review['expires_at']); ?></p><ul><?php foreach ($review['recipients'] as $channel=>$targets): if (!$targets) { continue; } ?><li><?php echo $e(str_replace('_',' ',$channel)); ?> · <?php echo $e(implode(', ',$targets)); ?></li><?php endforeach; ?></ul>
<ul><?php foreach ($review['history'] as $event): ?><li><?php echo $e($event['at'].' · '.$event['person'].' · '.str_replace('_',' ',$event['action'])); ?></li><?php endforeach; ?></ul>
<?php if ($review['state']==='awaiting_approval'): $expired=strtotime($review['expires_at'])<=time(); if ($expired): ?><p class="ops-notice">This approval expired. Approve and submit are unavailable. Reject the unsubmitted review before creating a replacement.</p><?php endif; ?><div class="ops-actions"><button type="button" class="btn btn-default" data-approval="<?php echo $e($review['id']); ?>" data-approval-action="approve" <?php echo $expired?'disabled':''; ?>>Approve wording and recipients</button><button type="button" class="btn btn-primary" data-approval="<?php echo $e($review['id']); ?>" data-approval-action="submit" <?php echo $expired?'disabled':''; ?>>Submit approved announcement</button><button type="button" class="btn btn-default" data-approval="<?php echo $e($review['id']); ?>" data-approval-action="reject">Reject unsubmitted request</button></div><?php endif; ?></details><?php endforeach; ?></div><?php endif; ?>
<?php if (!empty($enterprise['drills'])): ?><div class="ops-card"><div class="ops-heading"><h3>Assigned drills and reviews</h3><button type="button" class="btn btn-default btn-sm" id="ops-drill-report">Export assigned report</button></div><p class="ops-muted">A drill launch sends a test incident to its reviewed audience. Review completion records an observation; it does not prove delivery, playback or safety.</p>
<?php foreach ($enterprise['drills'] as $drill): ?><details><summary><?php echo $e($drill['name']); ?> <span class="ops-badge"><?php echo $e(str_replace('_',' ',$drill['status'])); ?></span></summary><p class="ops-muted">Due <?php echo $e($drill['due_at']); ?></p><ul><?php foreach ($drill['objectives'] as $objective): ?><li><?php echo $e($objective); ?></li><?php endforeach; ?></ul>
<?php if ($drill['can_launch']): ?><button type="button" class="btn btn-primary" data-drill-start="<?php echo $e($drill['id']); ?>">Review and launch drill</button><?php endif; ?>
<?php foreach ($drill['runs'] as $run): ?><div class="ops-heading"><p><strong><?php echo $e(str_replace('_',' ',$run['state'])); ?></strong><br><span class="ops-muted"><?php echo $e($run['created_at']); ?> · <?php echo count($run['reviews']); ?> saved review(s)<?php if (!empty($run['incident_id'])): ?> · <?php echo $e($run['incident_id']); ?><?php endif; ?></span></p><?php if ($drill['enabled']): ?><button type="button" class="btn btn-default btn-sm" data-drill-review="<?php echo $e($run['id']); ?>" data-drill-assignment="<?php echo $e($drill['id']); ?>">Record objective review</button><?php endif; ?></div><?php foreach ($run['reviews'] as $review): ?><p class="ops-muted"><?php echo $e($review['at'].' · '.$review['person']); ?> · <?php echo count(array_filter($review['completed'])); ?>/<?php echo count($review['completed']); ?> objectives completed<?php if ($review['note']!==''): ?><br><?php echo $e($review['note']); ?><?php endif; ?></p><?php endforeach; ?><?php endforeach; ?></details><?php endforeach; ?></div><?php endif; ?>
<?php if (!empty($enterprise['floorplans'])): ?><div class="ops-card"><h3>Assigned private floor plans</h3><p class="ops-muted">Select an assigned incident to see its human responses on a saved plan. Unconfirmed markers remain unconfirmed.</p><div class="ops-actions"><?php foreach ($enterprise['floorplans'] as $plan): ?><button type="button" class="btn btn-default" data-floorplan="<?php echo $e($plan['id']); ?>" <?php echo empty($state['incidents'])?'disabled':''; ?>><?php echo $e($plan['name']); ?></button><?php endforeach; ?></div></div><?php endif; ?>
<?php endif; ?>
<div class="ops-card"><h3><i class="fa fa-clipboard" aria-hidden="true"></i> Assigned incidents and roll call</h3>
<?php foreach ($state['incidents'] as $incident): ?><details><summary><?php echo $e($incident['title']); ?> <span class="ops-badge"><?php echo $e($incident['state']); ?><?php echo $incident['is_test'] ? ' · drill' : ''; ?></span></summary><p class="ops-muted"><?php echo $e($incident['created_at']); ?> · <?php echo $incident['response_counts']['expected']; ?> assigned people · <?php echo $incident['response_counts']['safe']; ?> safe · <?php echo $incident['response_counts']['needs_assistance']; ?> need assistance · <?php echo $incident['response_counts']['no_response']; ?> no human response</p>
<?php if (in_array('awaiting_approval',$incident['submission_states']??[],true)): ?><p class="ops-notice">An incident message is awaiting approval. Submit or reject its review before sending another update. Its pending message has not started delivery.</p><?php endif; ?>
<?php if (in_array('uncertain',$incident['submission_states']??[],true)): ?><p class="ops-notice">A submission could not confirm its result. Review saved delivery evidence before resending.</p><?php endif; ?>
<div class="ops-table"><table><thead><tr><th>Person</th><th>Location</th><th>Human response</th><?php if ($state['can_roll_call']): ?><th>Action</th><?php endif; ?></tr></thead><tbody><?php foreach ($incident['roster'] as $person): $response=$incident['responses'][$person['id']] ?? []; ?><tr><td><?php echo $e($person['name']); ?></td><td><?php echo $e($person['location']); ?></td><td><?php echo $e(str_replace('_', ' ', $response['response'] ?? 'no_response')); ?><?php if (!empty($response['note'])): ?><p class="ops-muted"><?php echo $e($response['note']); ?></p><?php endif; ?></td><?php if ($state['can_roll_call']): ?><td><?php if ($incident['state'] === 'open'): ?><button type="button" class="btn btn-default btn-sm" data-incident="<?php echo $e($incident['id']); ?>" data-person="<?php echo $e($person['id']); ?>">Record response</button><?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?></tbody></table></div>
<?php if ($incident['can_update'] && $incident['state'] === 'open'): ?><button type="button" class="btn btn-default" data-update="<?php echo $e($incident['id']); ?>"><i class="fa fa-bullhorn" aria-hidden="true"></i> Send update or all-clear</button><?php endif; ?></details><?php endforeach; ?>
<?php if (!$state['incidents']): ?><p class="ops-muted">No incidents on this page fall within your assignments.</p><?php endif; ?>
<?php if ($state['next_cursor']): ?><a class="btn btn-default" href="<?php echo $e($endpoint ?? 'config.php?display=slsmassnotifyserver_operations'); ?>&amp;cursor=<?php echo $e(rawurlencode($state['next_cursor'])); ?>">Older incident records</a><?php endif; ?></div>
<div id="ops-modal" class="ops-modal" hidden><form class="ops-dialog" role="dialog" aria-modal="true" aria-labelledby="ops-modal-title"><div class="ops-heading"><h3 id="ops-modal-title"></h3><button type="button" data-close class="btn btn-default" aria-label="Close"><i class="fa fa-times" aria-hidden="true"></i></button></div><div id="ops-modal-body"></div><div class="ops-actions"><button type="submit" class="btn btn-primary" id="ops-modal-submit">Save</button><button type="button" data-close class="btn btn-default">Cancel</button></div><p id="ops-modal-status" class="ops-status" role="status" aria-live="polite"></p></form></div>
</div></div></div></div>
<script type="application/json" id="sls-operations-data"><?php echo json_encode(['state'=>$state, 'csrf'=>$csrf_token, 'endpoint'=>$endpoint ?? 'config.php?display=slsmassnotifyserver_operations'], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR); ?></script>
<script><?php readfile(__DIR__.'/operations.js'); ?></script>
