<?php $e = static fn($v): string => htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>
<style><?php readfile(__DIR__.'/operators.css'); ?></style>
<div class="container-fluid sls-operator-container"><div class="display full-border"><div class="fpbx-container"><div id="sls-operator-access" class="sls-ops">
<div class="ops-heading"><div><h2><i class="fa fa-user-secret" aria-hidden="true"></i> SLS Operator Access <?php include __DIR__.'/labs.php'; ?></h2><p class="ops-muted">Create secure portal logins and assign their actions and recipients.</p></div><a class="btn btn-default" href="/mass-notify/" target="_blank" rel="noopener noreferrer"><i class="fa fa-external-link" aria-hidden="true"></i> Open operator portal</a></div>
<div class="ops-card"><h3><i class="fa fa-shield" aria-hidden="true"></i> Portal availability</h3><label class="ops-check"><input id="ops-portal-enabled" type="checkbox" <?php echo $state['access']['portal_enabled'] ? 'checked' : ''; ?>> Enable operator portal</label><p class="ops-muted">Disabled by default. Enable this to allow sign-in at /mass-notify/. Disabling it blocks portal requests and revokes operator sessions and queued delivery permissions.</p><?php if (!$state['access']['portal_enabled']): ?><p class="ops-notice" role="status">This feature has not been enabled.</p><?php endif; ?></div>
<div class="ops-notice"><i class="fa fa-shield" aria-hidden="true"></i> Operators sign in at <strong>/mass-notify/</strong> using their own password and authenticator. These accounts do not grant PBX or UCP access. Initial passwords must be changed at first sign-in. Resetting a password or authenticator revokes existing sessions.</div>
<div class="ops-card"><label class="ops-check"><input id="ops-enforce" type="checkbox" <?php echo $state['access']['enabled'] ? 'checked' : ''; ?>> Restrict other PBX users to assigned SLS roles</label><p class="ops-muted">Dedicated portal logins always use their saved permissions. Full PBX administrators retain access to this account editor.</p></div>
<?php foreach ($state['directory']['warnings'] as $warning): ?><div class="ops-notice ops-error"><?php echo $e($warning); ?></div><?php endforeach; ?>
<div class="ops-card"><div class="ops-heading"><h3><i class="fa fa-users" aria-hidden="true"></i> Operator logins</h3><button id="ops-add" type="button" class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> Add account</button></div><div id="ops-accounts"></div><p class="ops-muted">Permission changes take effect immediately and are checked again before queued delivery. Personal devices are assigned explicitly; a username never implies ownership of a phone or desktop.</p></div>
<div class="ops-actions"><button id="ops-save" type="button" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save accounts</button><span id="ops-result" role="status" aria-live="polite" class="ops-status"></span></div>
<div class="ops-card"><h3><i class="fa fa-shield" aria-hidden="true"></i> Authentication and security activity</h3><p class="ops-muted">Recent operator sign-ins, authentication failures, password recovery and administrator security events. Control API key use is shown under Help.</p>
<?php $activity=$state['security_activity']??['events'=>[],'notices'=>[]]; foreach($activity['notices'] as $notice): ?><p class="ops-notice" role="status"><?php echo $e($notice); ?></p><?php endforeach; ?>
<?php if(!$activity['events']): ?><p class="ops-muted">No security activity has been recorded.</p><?php else: ?><div class="ops-audit-scroll"><table class="table table-condensed table-striped"><thead><tr><th>Time</th><th>Source</th><th>Actor</th><th>Operator account</th><th>Activity</th><th>Result</th><th>IP</th></tr></thead><tbody>
<?php foreach($activity['events'] as $event): ?><tr><td><?php echo $e($event['created_at']); ?></td><td><?php echo $e($event['source']); ?></td><td><?php echo $e($event['actor']); ?></td><td><?php echo $e(($event['operator_username']??'').(isset($event['operator_id'])?' ('.$event['operator_id'].')':'')); ?></td><td><?php echo $e($event['label']); ?></td><td><?php echo $e(($event['ok']?'Accepted':'Rejected').' ('.$event['status'].')'); ?></td><td><?php echo $e($event['ip']); ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></div>
<div id="ops-modal" class="ops-modal" hidden><form class="ops-dialog" role="dialog" aria-modal="true" aria-labelledby="ops-editor-title"><div class="ops-heading"><h3 id="ops-editor-title">Operator account</h3><button type="button" class="btn btn-default" data-close aria-label="Close account editor"><i class="fa fa-times" aria-hidden="true"></i></button></div><div id="ops-editor"></div><div class="ops-actions"><button type="submit" class="btn btn-primary"><i class="fa fa-check" aria-hidden="true"></i> Keep changes</button><button type="button" class="btn btn-default" data-close>Cancel</button></div><p id="ops-editor-error" role="alert" class="ops-status"></p></form></div>
<div id="ops-reset-modal" class="ops-modal" hidden><section class="ops-dialog" role="dialog" aria-modal="true" aria-labelledby="ops-reset-title"><div class="ops-heading"><h3 id="ops-reset-title"><i class="fa fa-key" aria-hidden="true"></i> Password reset link</h3><button type="button" class="btn btn-default" data-reset-close aria-label="Close reset link"><i class="fa fa-times" aria-hidden="true"></i></button></div><p>This link works once and requires the operator’s existing authenticator code. Share it privately. A replacement link revokes the previous link.</p><label class="ops-field">Reset link<input id="ops-reset-url" type="text" readonly autocomplete="off" spellcheck="false"></label><p id="ops-reset-expiry" class="ops-muted"></p><div class="ops-actions"><button id="ops-reset-copy" type="button" class="btn btn-primary"><i class="fa fa-copy" aria-hidden="true"></i> Copy link</button><button type="button" class="btn btn-default" data-reset-close>Close</button></div><p id="ops-reset-result" class="ops-status" role="status" aria-live="polite"></p></section></div>
</div></div></div></div>
<script type="application/json" id="sls-operator-data"><?php echo json_encode(['state'=>array_diff_key($state,['security_activity'=>true]), 'csrf'=>$csrf_token, 'endpoint'=>$endpoint ?? 'config.php?display=slsmassnotifyserver_operators'], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR); ?></script>
<script><?php readfile(__DIR__.'/operators.js'); ?></script>
