(()=>{'use strict';const root=document.getElementById('sls-operations');if(!root)return;const data=JSON.parse(document.getElementById('sls-operations-data').textContent),state=data.state,form=root.querySelector('#ops-compose'),modal=root.querySelector('#ops-modal'),body=root.querySelector('#ops-modal-body'),modalForm=modal.querySelector('form'),modalStatus=root.querySelector('#ops-modal-status');let returnFocus=null,handler=null;const requestId=()=>{const a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map(v=>v.toString(16).padStart(2,'0')).join('');};
function node(tag,text,attrs={}){const n=document.createElement(tag);n.textContent=text||'';Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;}
function field(label,control){const n=node('label',label,{class:'ops-field'});n.append(control);body.append(n);return control;}
function select(options){const n=node('select');options.forEach(([value,label])=>n.append(node('option',label,{value})));return n;}
async function call(action,payload){const response=await fetch(data.endpoint||'config.php?display=slsmassnotifyserver_operations',{method:'POST',credentials:'same-origin',cache:'no-store',body:new URLSearchParams({slsmassnotifyserver_action:action,slsmassnotifyserver_csrf:data.csrf,payload:JSON.stringify(payload)})}),result=await response.json();if(!response.ok||(!result.success&&!(action==='job'&&result.job_id)))throw new Error([result.message,...(result.errors||[])].filter(Boolean).join('\n')||'The request was rejected.');return result;}
function close(){if(root.querySelector('#ops-modal-submit').disabled)return;modal.hidden=true;handler=null;body.oninput=null;if(returnFocus)returnFocus.focus();}
root.querySelectorAll('[data-close]').forEach(n=>n.addEventListener('click',close));modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const a=[...modal.querySelectorAll('button,input,select,textarea')].filter(n=>!n.disabled&&n.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1].focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0].focus();}}});
function open(title,label){returnFocus=document.activeElement;body.oninput=null;body.replaceChildren();modalStatus.textContent='';root.querySelector('#ops-modal-submit').disabled=false;root.querySelector('#ops-modal-title').textContent=title;root.querySelector('#ops-modal-submit').textContent=label;modal.hidden=false;modalForm.querySelector('button').focus();}
modalForm.addEventListener('submit',async e=>{e.preventDefault();if(!handler)return;const button=root.querySelector('#ops-modal-submit');button.disabled=true;modalStatus.textContent='Submitting…';try{if(await handler()===false){button.disabled=false;}else{location.reload();}}catch(error){modalStatus.textContent=error.message;button.disabled=false;}});
if(form){let reviewed='',sent=false,deliveryGeneration=0;const submit=root.querySelector('#ops-submit'),preview=root.querySelector('#ops-preview'),status=root.querySelector('#ops-compose-status');
const scheduling=()=>state.can_schedule&&(!state.can_send||form.elements.submission_mode?.value==='schedule');
function timing(){const fields=root.querySelector('#ops-schedule-fields');if(fields){fields.hidden=!scheduling();fields.querySelectorAll('input,select').forEach(n=>n.disabled=!scheduling());}submit.textContent=scheduling()?'Save schedule':'Send announcement';}
timing();
root.querySelector('#ops-tones').hidden=!form.elements.audio_mode.value.startsWith('tones');
Object.entries(state.tone_defaults||{}).forEach(([key,value])=>{if([...form.elements[key].options].some(o=>o.value===value))form.elements[key].value=value;});
async function trackJob(id){
 const panel=root.querySelector('#ops-delivery-results');if(!panel)return;panel.hidden=false;
 const generation=++deliveryGeneration,deadline=Date.now()+600000;
 while(generation===deliveryGeneration&&Date.now()<deadline){
  if(document.hidden){await new Promise(resolve=>setTimeout(resolve,5000));continue;}
  try{const result=await call('job',{job_id:id});
   if(generation!==deliveryGeneration)return;
   panel.replaceChildren(node('strong','Delivery · '+result.state.replaceAll('_',' ')));
   Object.values(result.receipts||{}).forEach(row=>panel.append(node('p',[row.channel,row.target,row.state,row.detail||row.message].filter(Boolean).join(' · '))));
   if(!Object.keys(result.receipts||{}).length)panel.append(node('p',result.message||'Waiting for channel results.'));
   const pending=Object.values(result.receipts||{}).some(row=>row.channel==='desktop'&&row.state==='published');
   if(['complete','failed','partial_or_failed','expired'].includes(result.state)&&!pending)return;
  }catch(error){if(generation===deliveryGeneration)panel.append(node('p',error.message));return;}
  await new Promise(resolve=>setTimeout(resolve,2000));
 }
 if(generation===deliveryGeneration)panel.append(node('p','Automatic receipt refresh ended. Administrators can review the saved job in Delivery details.'));
}
function payload(){const delivery={style:form.elements.style.value,background_color:form.elements.background_color.value,audio_mode:form.elements.audio_mode.value,opening_tone:form.elements.opening_tone.value,closing_tone:form.elements.closing_tone.value};Object.keys(state.choices).forEach(key=>{delivery[key]=[...form.querySelectorAll('[data-channel="'+key+'"]:checked')].map(n=>n.value);});return{delivery,title:form.elements.title.value.trim(),message:form.elements.message.value.trim(),...(scheduling()?{name:form.elements.schedule_name.value.trim(),occurrences:[form.elements.run_at.value],recurrence_mode:form.elements.recurrence_mode.value,lateness_minutes:Number(form.elements.lateness_minutes.value)}:{})};}form.addEventListener('input',()=>{timing();root.querySelector('#ops-color').hidden=form.elements.style.value!=='colored';reviewed='';submit.disabled=true;preview.hidden=true;if(sent){sent=false;root.querySelector('#ops-review').disabled=false;}const tones=form.elements.audio_mode.value.startsWith('tones');root.querySelector('#ops-tones').hidden=!tones;if(!tones){form.elements.opening_tone.value='';form.elements.closing_tone.value='';}});form.addEventListener('submit',async e=>{e.preventDefault();const p=payload(),count=Object.keys(state.choices).reduce((n,k)=>n+p.delivery[k].length,0);if(!count){status.textContent='Select at least one recipient.';return;}const button=root.querySelector('#ops-review');button.disabled=true;try{if(state.can_send)await call('preview',p);reviewed=JSON.stringify(p);preview.textContent=p.title+'\n\n'+p.message+'\n\n'+count+' selected destination(s) · '+p.delivery.audio_mode.replaceAll('_',' ');preview.hidden=false;status.textContent='Review the message and selected recipients before submitting.';submit.disabled=false;}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});submit.addEventListener('click',async()=>{const p=payload();if(JSON.stringify(p)!==reviewed||sent)return;submit.disabled=true;root.querySelector('#ops-review').disabled=true;try{const result=await call(scheduling()?'save_schedule':'send',p);status.textContent=result.message||'Submission accepted. Sent announcements cannot be edited or cancelled.';sent=true;reviewed='';if(result.job_id)trackJob(result.job_id);}catch(error){status.textContent=error.message;root.querySelector('#ops-review').disabled=false;reviewed='';}});}
root.querySelectorAll('[data-template]').forEach(button=>button.addEventListener('click',()=>{const t=state.templates.find(r=>r.id===button.dataset.template),id=requestId();open('Launch · '+t.name,'Launch incident');const controls={};t.fields.forEach(r=>controls[r.key]=field(r.label,node('input','',{maxlength:'120',required:'required'})));const drillBox=node('label','',{class:'ops-check'}),drill=node('input','',{type:'checkbox'});drillBox.append(drill,node('span','This is a drill / test'));body.append(drillBox);const language=field('Reviewed language',select([['','Default wording'],...(t.language_variants||[]).map(r=>[r.locale,r.name])]));const review=node('div','',{class:'ops-preview'});body.append(review);function update(){const variant=t.language_variants.find(r=>r.locale===language.value)||t;let title=variant.title,message=variant.message;t.fields.forEach(r=>{title=title.replaceAll('{{'+r.key+'}}',controls[r.key].value);message=message.replaceAll('{{'+r.key+'}}',controls[r.key].value);});review.textContent=(drill.checked?'DRILL / TEST\n':'')+title+'\n\n'+message;}body.oninput=update;update();handler=()=>call('start_incident',{template_id:t.id,request_id:id,fields:Object.fromEntries(Object.entries(controls).map(([k,n])=>[k,n.value.trim()])),is_test:drill.checked,language_variant:language.value});}));
root.querySelectorAll('[data-person]').forEach(button=>button.addEventListener('click',()=>{const incident=state.incidents.find(r=>r.id===button.dataset.incident),person=incident.roster.find(r=>r.id===button.dataset.person),id=requestId();open('Record response · '+person.name,'Record response');const response=field('Human response',select([['safe','Safe / accounted for'],['needs_assistance','Needs assistance'],['missing','Missing / not accounted for'],['received','Person confirms receipt']])),note=field('Optional observation',node('textarea','',{maxlength:'500'}));handler=()=>call('roll_call',{incident_id:incident.id,person_id:person.id,request_id:id,response:response.value,note:note.value.trim()});}));
root.querySelectorAll('[data-update]').forEach(button=>button.addEventListener('click',()=>{const id=requestId();open('Incident update','Send announcement');const kind=field('Update type',select([['update','Update'],['all_clear','All-clear']])),message=field('Approved message',node('textarea','',{maxlength:'500',required:'required'}));body.append(node('p','All-clear closes the incident and sends a separate announcement. Previous messages retain their delivery history.',{class:'ops-muted'}));handler=()=>call('update_incident',{incident_id:button.dataset.update,request_id:id,kind:kind.value,message:message.value.trim()});}));
root.querySelectorAll('[data-remove-schedule]').forEach(button=>button.addEventListener('click',()=>{open('Remove your schedule','Remove future occurrences');body.append(node('p','This removes future occurrences. Delivery that was already submitted keeps its history.'));handler=()=>call('remove_schedule',{schedule_id:button.dataset.removeSchedule});}));
const enterprise=state.enterprise||{approvals:[],drills:[],floorplans:[]};
root.querySelectorAll('[data-approval]').forEach(button=>button.addEventListener('click',()=>{const review=enterprise.approvals.find(r=>r.id===button.dataset.approval),action=button.dataset.approvalAction;open(action==='approve'?'Approve frozen announcement':action==='submit'?'Submit approved announcement':'Reject unsubmitted announcement',button.textContent);body.append(node('strong',review.title),node('p',review.message,{class:'ops-review-copy'}));Object.entries(review.recipients).forEach(([channel,ids])=>{if(ids.length)body.append(node('p',channel.replaceAll('_',' ')+' · '+ids.join(', ')));});body.append(node('p',action==='approve'?'Your approval is attributed to this login and expires with the request.':action==='submit'?'The server checks two distinct current approvers before it starts delivery.':'Rejection closes this unsubmitted review. Previously submitted delivery retains its history.',{class:'ops-muted'}));handler=()=>call('approval_'+action,{review_id:review.id});}));
root.querySelectorAll('[data-drill-start]').forEach(button=>button.addEventListener('click',()=>{const assignment=enterprise.drills.find(r=>r.id===button.dataset.drillStart),template=state.templates.find(r=>r.id===assignment.template_id),id=requestId();if(!template)return;open('Launch assigned drill · '+assignment.name,'Launch test incident');const controls={};template.fields.forEach(r=>controls[r.key]=field(r.label,node('input','',{maxlength:'120',required:'required'})));const review=node('div','',{class:'ops-preview'});body.append(review,node('p','This sends a DRILL / TEST incident to the reviewed template audience. Any configured approval policy still applies.',{class:'ops-muted'}));function update(){let title=template.title,message=template.message;template.fields.forEach(r=>{title=title.replaceAll('{{'+r.key+'}}',controls[r.key].value);message=message.replaceAll('{{'+r.key+'}}',controls[r.key].value);});review.textContent='DRILL / TEST\n'+title+'\n\n'+message;}body.oninput=update;update();handler=()=>call('drill_start',{assignment_id:assignment.id,request_id:id,fields:Object.fromEntries(Object.entries(controls).map(([key,n])=>[key,n.value.trim()]))});}));
root.querySelectorAll('[data-drill-review]').forEach(button=>button.addEventListener('click',()=>{const assignment=enterprise.drills.find(r=>r.id===button.dataset.drillAssignment),run=assignment.runs.find(r=>r.id===button.dataset.drillReview);open('Record drill review · '+assignment.name,'Save attributable review');const flags=(run.assignment.objectives||[]).map(objective=>{const label=node('label','',{class:'ops-check ops-drill-objective'}),flag=node('input','',{type:'checkbox'});label.append(flag,node('span',objective));body.append(label);return flag;});const note=field('Observation or follow-up',node('textarea','',{maxlength:'1000'}));body.append(node('p','Checked objectives record your observation. They do not change delivery receipts or human safety responses.',{class:'ops-muted'}));handler=()=>call('drill_review',{run_id:run.id,completed:flags.map(n=>n.checked),note:note.value.trim()});}));
root.querySelector('#ops-drill-report')?.addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;try{const report=await call('drill_report',{}),url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)+'\n'],{type:'application/json'})),download=node('a','',{href:url,download:'sls-assigned-drill-report.json'});document.body.append(download);download.click();download.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){open('Drill report unavailable','Close');body.append(node('p',error.message));handler=async()=>{modal.hidden=true;return false;};}finally{button.disabled=false;}});
root.querySelectorAll('[data-floorplan]').forEach(button=>button.addEventListener('click',()=>{const plan=enterprise.floorplans.find(r=>r.id===button.dataset.floorplan);open('Human responses · '+plan.name,'Load or refresh overlay');const incident=field('Assigned incident',select(state.incidents.map(r=>[r.id,r.title+' · '+r.state]))),output=node('div');body.append(output);handler=async()=>{const overlay=await call('floorplan_overlay',{plan_id:plan.id,incident_id:incident.value}),image=await call('floorplan_image',{image_id:overlay.plan.image_id});if(!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(image.image))throw new Error('The private image response is invalid.');output.replaceChildren(node('p',overlay.meaning,{class:'ops-muted'}),node('p','Observed '+overlay.observed_at));const figure=node('div','',{class:'ops-floorplan'}),picture=node('img','',{src:image.image,alt:plan.name}),legend=node('ul');figure.append(picture);overlay.plan.markers.forEach(marker=>{const status=marker.status.replaceAll('_',' '),counts=Object.entries(marker.response_counts||{}).map(([key,value])=>key.replaceAll('_',' ')+': '+value).join(', '),label=marker.label+' · '+status+(counts?' · '+counts:'');const dot=node('span','',{class:'ops-floorplan-marker','data-status':marker.status,title:label,role:'img','aria-label':label});dot.style.left=Number(marker.x)+'%';dot.style.top=Number(marker.y)+'%';figure.append(dot);legend.append(node('li',label));});output.append(figure,legend);modalStatus.textContent='Overlay loaded. Human responses remain separate from transport receipts.';return false;};}));})();
