<?php
declare(strict_types=1);
require_once __DIR__.'/../slsmassnotifyserver/EnterpriseIdentityOidc.php';
require_once __DIR__.'/../slsmassnotifyserver/EnterpriseIdentitySaml.php';
require_once __DIR__.'/../slsmassnotifyserver/EnterpriseIdentity.php';
require_once __DIR__.'/../slsmassnotifyserver/DirectorySync.php';
require_once __DIR__.'/../slsmassnotifyserver/SubscriberService.php';
require_once __DIR__.'/../slsmassnotifyserver/IncidentService.php';
use SLS\MassNotify\{EnterpriseIdentity,EnterpriseIdentityConfig,EnterpriseIdentityHttp,EnterpriseIdentityStore,EnterpriseIdentityOidc,EnterpriseIdentitySaml,DirectoryConfig,DirectorySync,SubscriberConfig,SubscriberService,IncidentConfig,IncidentStore,IncidentService};
use Firebase\JWT\JWT;
use OneLogin\Saml2\{Constants,Utils};
use RobRichards\XMLSecLibs\{XMLSecurityKey,XMLSecurityDSig};
function check($ok,string $why):void{if(!$ok){throw new RuntimeException($why);}}
function reject(callable $fn,string $why):void{try{$fn();}catch(Throwable $e){return;}throw new RuntimeException($why);}
function b64(string $s):string{return rtrim(strtr(base64_encode($s),'+/','-_'),'=');}
$root=sys_get_temp_dir().'/sls-identity-'.bin2hex(random_bytes(8));mkdir($root,0700);register_shutdown_function(static function()use($root):void{$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $file){$p=$file->getPathname();if($file->isDir()&&!$file->isLink()){rmdir($p);}else{unlink($p);}}rmdir($root);});
$now=time();$store=new EnterpriseIdentityStore($root.'/state');$browser=str_repeat('b',64);
check(!EnterpriseIdentityConfig::normalize([])['enabled']&&!DirectoryConfig::normalize([])['enabled']&&!SubscriberConfig::normalize([])['enabled'],'Features enabled by default');
$state=$store->reserve(['provider_id'=>'fixture'],$browser,$now);check($store->take($state,$browser,$now)['provider_id']==='fixture','Valid browser transaction rejected');check(isset($store->take($state,$browser,$now)['invalid']),'Replayed transaction accepted');
$state=$store->reserve(['provider_id'=>'fixture'],$browser,$now);check(isset($store->take($state,str_repeat('c',64),$now)['invalid']),'Browser CSRF binding bypass');check(isset($store->take($state,$browser,$now)['invalid']),'Rejected browser attempt did not consume transaction');
$state=$store->reserve(['provider_id'=>'fixture'],$browser,$now);check(isset($store->take($state,$browser,$now+301)['invalid']),'Expired state accepted');
$store->replay('assertion', $now+60,$now);reject(fn()=>$store->replay('assertion',$now+60,$now),'Assertion replay accepted');
// Lost/corrupt ledger must fail closed and preserve evidence.
$raw=file_get_contents($root.'/state/replay.json');unlink($root.'/state/replay.json');reject(fn()=>$store->replay('assertion',$now+60,$now),'Missing ledger silently reset');file_put_contents($root.'/state/replay.json',$raw);chmod($root.'/state/replay.json',0600);
file_put_contents($root.'/state/replay.json','{"duplicate":1,"duplicate":2}');reject(fn()=>$store->replay('new',$now+60,$now),'Duplicate JSON keys accepted');file_put_contents($root.'/state/replay.json',$raw);
$target=$root.'/outside';file_put_contents($target,'unchanged');chmod($target,0600);symlink($target,$root.'/state/unsafe.lock');reject(fn()=>$store->transaction('unsafe',static fn(&$r)=>null),'Symlink lock accepted');check(file_get_contents($target)==='unchanged','Symlink target touched');
posix_mkfifo($root.'/state/fifo.lock',0600);$began=microtime(true);reject(fn()=>$store->transaction('fifo',static fn(&$r)=>null),'FIFO lock accepted');check(microtime(true)-$began<1,'FIFO opened and blocked');
$other=new EnterpriseIdentityStore($root.'/other');rename($root.'/other',$root.'/other-lost');reject(fn()=>new EnterpriseIdentityStore($root.'/other'),'Deleted established state was recreated');rename($root.'/other-lost',$root.'/other');
$key=openssl_pkey_new(['private_key_type'=>OPENSSL_KEYTYPE_RSA,'private_key_bits'=>2048]);openssl_pkey_export($key,$private);$details=openssl_pkey_get_details($key);
$csr=openssl_csr_new(['commonName'=>'Fixture IdP'],$key,['digest_alg'=>'sha256']);$cert=openssl_csr_sign($csr,null,$key,2,['digest_alg'=>'sha256']);openssl_x509_export($cert,$pem);
$jwks=['keys'=>[['kty'=>'RSA','alg'=>'RS256','use'=>'sig','kid'=>'fixture','n'=>b64($details['rsa']['n']),'e'=>b64($details['rsa']['e'])]]];
$tokenClaims=['iss'=>'https://idp.example.test','aud'=>'fixture-client','sub'=>'immutable-42','nonce'=>str_repeat('n',64),'iat'=>$now,'exp'=>$now+300];
$p=['id'=>'idp_'.str_repeat('a',24),'vendor'=>'okta','protocol'=>'oidc','name'=>'Fixture','enabled'=>true,'issuer'=>'https://idp.example.test','callback_url'=>'https://pbx.example.test/mass-notify/sso.php',
    'discovery_url'=>'https://idp.example.test/.well-known/openid-configuration','client_id'=>'fixture-client','client_secret'=>'fixture-secret','token_auth'=>'client_secret_basic','endpoint_hosts'=>['idp.example.test'],'hosted_domain'=>''];
$p=EnterpriseIdentityConfig::normalize(['providers'=>[$p]])['providers'][0];$validToken=JWT::encode($tokenClaims,$private,'RS256','fixture');
check(EnterpriseIdentityOidc::verify($validToken,$jwks,$p,$tokenClaims['nonce'],$now)['sub']==='immutable-42','Valid signed OIDC token rejected');
foreach([['iss'=>'https://other.example.test'],['aud'=>'other-client'],['nonce'=>'other'],['exp'=>$now-90],['iat'=>$now+90],['iat'=>$now-601],['sub'=>''],['aud'=>['fixture-client','another'],'azp'=>'another'],['exp'=>(string)($now+300)],['nbf'=>$now+90]] as $bad){$claims=array_replace($tokenClaims,$bad);reject(fn()=>EnterpriseIdentityOidc::verify(JWT::encode($claims,$private,'RS256','fixture'),$jwks,$p,$tokenClaims['nonce'],$now),'Bad OIDC claim accepted: '.json_encode($bad));}
reject(fn()=>EnterpriseIdentityOidc::verify(JWT::encode($tokenClaims,'fixture-secret','HS256','fixture'),$jwks,$p,$tokenClaims['nonce'],$now),'HMAC algorithm confusion accepted');
reject(fn()=>EnterpriseIdentityOidc::verify($validToken,['keys'=>[$jwks['keys'][0],$jwks['keys'][0]]],$p,$tokenClaims['nonce'],$now),'Duplicate kid accepted');
foreach(EnterpriseIdentityConfig::VENDORS as $vendor){$vp=$p;$vp['vendor']=$vendor;if($vendor==='entra'){$vp['issuer']='https://login.microsoftonline.com/11111111-1111-1111-1111-111111111111/v2.0';$vp['discovery_url']=$vp['issuer'].'/.well-known/openid-configuration';$vp['endpoint_hosts']=['login.microsoftonline.com'];}
    elseif($vendor==='google'){$vp['issuer']='https://accounts.google.com';$vp['discovery_url']=$vp['issuer'].'/.well-known/openid-configuration';$vp['endpoint_hosts']=['accounts.google.com'];$vp['hosted_domain']='example.test';}
    elseif($vendor==='onelogin'){$vp['token_auth']='none';$vp['client_secret']='';}
    $vp=EnterpriseIdentityConfig::normalize(['providers'=>[$vp]])['providers'][0];$host=$vp['endpoint_hosts'][0];$d=['issuer'=>$vp['issuer'],'authorization_endpoint'=>'https://'.$host.'/authorize','token_endpoint'=>'https://'.$host.'/token','jwks_uri'=>'https://'.$host.'/keys','response_types_supported'=>['code'],'id_token_signing_alg_values_supported'=>['RS256'],'token_endpoint_auth_methods_supported'=>[$vp['token_auth']],'code_challenge_methods_supported'=>['S256']];$issuedClaims=null;$captured=null;
    $http=static function($url,$hosts,$method,$form,$headers)use($d,$vp,$jwks,$private,&$issuedClaims,&$captured){if($url===$vp['discovery_url']){return $d;}if($url===$d['token_endpoint']){$captured=$form;return ['id_token'=>JWT::encode($issuedClaims,$private,'RS256','fixture')];}if($url===$d['jwks_uri']){return $jwks;}throw new RuntimeException('Unexpected fixture HTTP');};
    $adapter=new EnterpriseIdentityOidc($http);$url=$adapter->begin($vp,$store,$browser,$now);parse_str(parse_url($url,PHP_URL_QUERY),$q);check($q['response_type']==='code'&&$q['code_challenge_method']==='S256','Code/PKCE downgrade');$tx=$store->take($q['state'],$browser,$now);check(b64(hash('sha256',$tx['verifier'],true))===$q['code_challenge'],'PKCE verifier not bound');
    $issuedClaims=array_replace($tokenClaims,['iss'=>$vp['issuer'],'nonce'=>$tx['nonce']]);if($vendor==='google'){$issuedClaims['hd']='example.test';}$proof=$adapter->finish($vp,$tx,'fixture-code',$store,$now);check($proof['subject']==='immutable-42'&&$captured['code_verifier']===$tx['verifier'],'Provider authorization code/PKCE completion failed: '.$vendor);
    reject(fn()=>$adapter->finish($vp,$tx,'fixture-code',$store,$now),'ID token replay accepted');
}
reject(fn()=>EnterpriseIdentityHttp::request('http://idp.example.test',['idp.example.test']),'Non-TLS endpoint accepted');reject(fn()=>EnterpriseIdentityHttp::request('https://other.example.test',['idp.example.test']),'Discovery SSRF hostname accepted');
// SAML positive signature plus wrapping/issuer/audience/request/time fixtures.
$sp=['id'=>$p['id'],'vendor'=>'okta','protocol'=>'saml','name'=>'SAML Fixture','enabled'=>true,'issuer'=>'https://idp.example.test/saml','callback_url'=>$p['callback_url'],'idp_sso_url'=>'https://idp.example.test/sso','sp_entity_id'=>'https://pbx.example.test/mass-notify','idp_signing_certificates'=>[$pem],'sp_certificate'=>$pem,'sp_private_key'=>$private,'nameid_format'=>Constants::NAMEID_PERSISTENT];
$sp=EnterpriseIdentityConfig::normalize(['providers'=>[$sp]])['providers'][0];$_SERVER+=['HTTP_HOST'=>'pbx.example.test','SERVER_PORT'=>443,'HTTPS'=>'on','SCRIPT_NAME'=>'/mass-notify/sso.php','REQUEST_URI'=>'/mass-notify/sso.php'];
function samlFixture(array $sp,string $private,string $cert,string $request,int $time,array $changes=[]):string {
 $a=['issuer'=>$sp['issuer'],'audience'=>$sp['sp_entity_id'],'request'=>$request,'recipient'=>$sp['callback_url'],'expiry'=>$time+300,'subject'=>'stable-saml-42'];$a=array_replace($a,$changes);$e=static fn($x)=>htmlspecialchars((string)$x,ENT_XML1|ENT_QUOTES);$at=gmdate('Y-m-d\TH:i:s\Z',$time);$before=gmdate('Y-m-d\TH:i:s\Z',$time-5);$after=gmdate('Y-m-d\TH:i:s\Z',$a['expiry']);
 $assertion='<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_assertion'.bin2hex(random_bytes(8)).'" Version="2.0" IssueInstant="'.$at.'"><saml:Issuer>'.$e($a['issuer']).'</saml:Issuer><saml:Subject><saml:NameID Format="'.$sp['nameid_format'].'">'.$e($a['subject']).'</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="'.$e($a['request']).'" NotOnOrAfter="'.$after.'" Recipient="'.$e($a['recipient']).'"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="'.$before.'" NotOnOrAfter="'.$after.'"><saml:AudienceRestriction><saml:Audience>'.$e($a['audience']).'</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="'.$at.'" SessionIndex="_session"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement></saml:Assertion>';
 $signed=Utils::addSign($assertion,$private,$cert,XMLSecurityKey::RSA_SHA256,XMLSecurityDSig::SHA256);$doc=new DOMDocument();$doc->loadXML($signed);$signature=$doc->getElementsByTagNameNS('http://www.w3.org/2000/09/xmldsig#','Signature')->item(0);$issuer=$doc->getElementsByTagNameNS('urn:oasis:names:tc:SAML:2.0:assertion','Issuer')->item(0);$doc->documentElement->removeChild($signature);$doc->documentElement->insertBefore($signature,$issuer->nextSibling);$signed=$doc->saveXML($doc->documentElement);
 return '<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_response'.bin2hex(random_bytes(8)).'" Version="2.0" IssueInstant="'.$at.'" Destination="'.$sp['callback_url'].'" InResponseTo="'.$e($a['request']).'"><saml:Issuer>'.$e($a['issuer']).'</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>'.$signed.'</samlp:Response>';
}
$saml=new EnterpriseIdentitySaml();$url=$saml->begin($sp,$store,$browser,$now);parse_str(parse_url($url,PHP_URL_QUERY),$q);check(isset($q['Signature'])&&$q['SigAlg']===XMLSecurityKey::RSA_SHA256,'SAML AuthnRequest not signed');$tx=$store->take($q['RelayState'],$browser,$now);$xml=samlFixture($sp,$private,$pem,$tx['request_id'],$now);
$debugAuth=new \OneLogin\Saml2\Auth(EnterpriseIdentitySaml::settings($sp));$_POST=['SAMLResponse'=>base64_encode($xml)];$debugAuth->processResponse($tx['request_id']);if($debugAuth->getErrors()){throw new RuntimeException('SAML fixture: '.$debugAuth->getLastErrorReason());}$_POST=[];$proof=$saml->finish($sp,$tx,base64_encode($xml),$store,$now);check($proof['subject']==='stable-saml-42','Valid signed SAML fixture rejected');reject(fn()=>$saml->finish($sp,$tx,base64_encode($xml),$store,$now),'SAML assertion replay accepted');
foreach([['issuer'=>'https://attacker.example.test'],['audience'=>'another-app'],['request'=>'_wrong-request'],['recipient'=>'https://other.example.test/acs'],['expiry'=>$now-300]] as $bad){$badXml=samlFixture($sp,$private,$pem,$tx['request_id'],$now,$bad);reject(fn()=>$saml->finish($sp,$tx,base64_encode($badXml),$store,$now),'Bad signed SAML accepted: '.json_encode($bad));}
reject(fn()=>$saml->finish($sp,$tx,base64_encode(str_replace('stable-saml-42','attacker',$xml)),$store,$now),'Tampered signed SAML accepted');
$wrapped=str_replace('</samlp:Response>','<saml:Assertion ID="_unsigned" Version="2.0" IssueInstant="'.gmdate('c',$now).'"/></samlp:Response>',$xml);reject(fn()=>$saml->finish($sp,$tx,base64_encode($wrapped),$store,$now),'SAML wrapping accepted');
reject(fn()=>$saml->finish($sp,$tx,base64_encode('<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]><x>&e;</x>'),$store,$now),'XXE accepted');
// Directory applies only a complete reviewed snapshot, retaining manual rows.
$template=IncidentConfig::template(['id'=>'tpl_'.str_repeat('d',24),'name'=>'Fixture','title'=>'Fixture incident','message'=>'Fixture message','delivery'=>['extensions'=>['1000']],'roster'=>[['id'=>'manual-person','name'=>'Manual Person']]]);
$source=DirectoryConfig::normalize(['sources'=>[['id'=>'dir_'.str_repeat('d',24),'name'=>'CSV fixture','type'=>'csv','enabled'=>true,'template_ids'=>[$template['id']],'sync_subscribers'=>true,'records'=>[]]]])['sources'][0];
$settings=['directory_sync'=>['schema'=>1,'enabled'=>true,'sources'=>[$source]],'incident_workflows'=>['schema'=>1,'templates'=>[$template]],'subscriber_browser'=>SubscriberConfig::defaults()];
$records=DirectorySync::csv("external_id,name,email,active\n42,Fixture Person,person@example.test,true\n");$plan=DirectorySync::plan($settings,$source,$records);check($settings['incident_workflows']['templates'][0]['roster']===[$template['roster'][0]],'Dry-run mutated original roster');$settings=DirectorySync::apply($settings,$source,$records);check(count($settings['incident_workflows']['templates'][0]['roster'])===2,'Directory import not applied');$pid=DirectoryConfig::personId($source['id'],'42');check($settings['incident_workflows']['templates'][0]['roster'][1]['id']===$pid,'Stable ID mismatch');$original=$settings;
$source=$settings['directory_sync']['sources'][0];$off=DirectorySync::apply($settings,$source,[]);check(count($off['incident_workflows']['templates'][0]['roster'])===1&&!$off['subscriber_browser']['people'][0]['enabled'],'Deprovisioning left active roster or subscriber');check(count($original['incident_workflows']['templates'][0]['roster'])===2,'Existing snapshot object mutated');
reject(fn()=>DirectorySync::csv("external_id,name\n42,One\n42,Two\n"),'Repeated external ID accepted');
$scim=['scim_base_url'=>'https://scim.example.test/v2','scim_token'=>'inert'];$scimHttp=static fn()=>['schemas'=>['urn:ietf:params:scim:api:messages:2.0:ListResponse'],'totalResults'=>2,'startIndex'=>1,'Resources'=>[]];reject(fn()=>DirectorySync::scim($scim,$scimHttp),'Partial SCIM allowed deprovisioning');
// An actual IncidentStore/Service verifies token ownership and immutable roster responses.
$settings['subscriber_browser']['enabled']=true;$settings['subscriber_browser']['public_base_url']='https://pbx.example.test/mass-notify/subscriber.php';$settings['subscriber_browser']['people'][0]['registered_at']=$now-30;
$istore=new IncidentStore($root.'/incidents');$fixtureTemplate=$settings['incident_workflows']['templates'][0];$incidentService=new IncidentService($istore,fn()=>$fixtureTemplate,fn($d)=>$d,fn()=>['success'=>true,'job_id'=>'job_'.str_repeat('1',32)],fn()=>[],fn()=>$now);
$incident=$incidentService->start(['template_id'=>$fixtureTemplate['id'],'request_id'=>str_repeat('f',32),'fields'=>[],'is_test'=>true],['identity'=>'Fixture admin']);$subscriber=new SubscriberService($store,$istore);$person=$settings['subscriber_browser']['people'][0];$issued=$subscriber->issue($settings,$person['id'],$incident['id'],$now);reject(fn()=>$subscriber->verify($settings,$issued['token'],$now),'Unaccepted email proof accepted');$subscriber->delivery($issued['token_hash'],'accepted');$bound=$subscriber->verify($settings,$issued['token'],$now);reject(fn()=>$subscriber->verify($settings,$issued['token'],$now),'One-use email proof replay accepted');
$reply=$subscriber->respond($settings,$bound,['request_id'=>str_repeat('1',32),'response'=>'safe','note'=>'Fixture safe'],$now);check($reply['response']['source']==='human_browser_response'&&$reply['response']['response']==='safe','Browser response confused with receipt/operator');check($istore->read($incident['id'])['template']['roster'][1]['id']===$pid,'Browser response modified roster');
reject(fn()=>$subscriber->respond($settings,$bound,['request_id'=>str_repeat('2',32),'person_id'=>'manual-person','response'=>'safe'],$now),'Cross-person response accepted');$changed=$settings;$changed['subscriber_browser']['people'][0]['version']=str_repeat('f',64);reject(fn()=>$subscriber->current($changed,$bound,$now),'Revoked version kept session');$changed=$settings;$changed['subscriber_browser']['people'][0]['registered_at']=$now+1;reject(fn()=>$subscriber->issue($changed,$person['id'],$incident['id'],$now),'Post-incident replacement identity admitted');
reject(fn()=>$subscriber->current($settings,$bound,$now+901),'Expired subscriber session accepted');
echo "Enterprise identity: five synthetic OIDC providers, signed SAML/attack fixtures, directory snapshots, subscriber ownership and protected-ledger failures passed.\n";
