<?php
declare(strict_types=1);
set_error_handler(static function($code,$message,$file,$line) { if(error_reporting()&$code) throw new ErrorException($message,0,$code,$file,$line); return false; });
require dirname(__DIR__).'/slsmassnotifyserver/EnterpriseIntegrationsService.php';
use SLS\MassNotify\{EnterpriseIntegrationsConfig as Config,EnterpriseIntegrationsProvider as Provider,EnterpriseIntegrationsService as Service,EnterpriseIntegrationsStore as Store,EnterprisePublicWarning as Cap};
function check(bool $ok,string $why): void { if(!$ok) throw new RuntimeException($why); }
function rejects(callable $call,string $message=''): void { try{$call();}catch(Throwable $e){ if($message!=='') check(str_contains($e->getMessage(),$message),'Wrong rejection: '.$e->getMessage()); return;} throw new RuntimeException('Expected rejection '.$message); }
class Fixture extends Provider {
 public array $calls=[]; public array $reply=['status'=>200,'error'=>0,'body'=>'{}'];
 protected function request(string $url,string $body,array $headers,?array $device=null):array { $this->calls[]=[$url,json_decode($body,true),$headers,$device]; return $this->reply; }
}
$temporary=sys_get_temp_dir().'/sls-integrations-'.bin2hex(random_bytes(8));mkdir($temporary,0700);
$directory=$temporary.'/journal';mkdir($directory,0700);
$now=time();$clock=$now;$provider=new Fixture();$store=new Store($directory);$service=new Service($store,$provider,static function()use(&$clock):int{return $clock;});
try {
 $config=Config::normalize([]);check($config['enabled']==='0','Master enabled by default');foreach($config as $section=>$row){if(is_array($row))check($row['enabled']==='0',$section.' enabled by default');}
 check(count(Config::catalog())===5,'Representative brand count');
 rejects(fn()=>Config::origin('http://controller.example.org','192.168.1.5'));
 rejects(fn()=>Config::origin('https://controller.example.org','127.0.0.1'));
 rejects(fn()=>Config::origin('https://controller.example.org/path','192.168.1.5'));
 rejects(fn()=>Config::origin('https://192.168.1.6','192.168.1.5'));
 Config::origin('https://controller.example.org','192.168.1.5');
 foreach(['zoom'=>['status'=>201,'body'=>['id'=>123,'join_url'=>'https://example.zoom.us/j/123','start_url'=>'secret-host-url']], 'google_meet'=>['status'=>200,'body'=>['name'=>'spaces/example','meetingUri'=>'https://meet.google.com/abc-defg-hij']], 'webex'=>['status'=>200,'body'=>['id'=>'meeting-id','webLink'=>'https://example.webex.com/meet/abc']]]as $brand=>$reply){
  $meeting=$config['meetings'];$meeting['enabled']='1';$meeting['provider']=$brand;$meeting[$brand==='google_meet'?'google_access_token':$brand.'_access_token']='fixture-token';
  $provider->reply=['status'=>$reply['status'],'error'=>0,'body'=>json_encode($reply['body'])];$receipt=$provider->meeting($meeting,'Fixture incident',$now+60,30);$last=$provider->calls[count($provider->calls)-1];
  check($receipt['state']==='accepted'&&!str_contains(json_encode($receipt),'fixture-token')&&!isset($receipt['start_url']),'Meeting leaked secret');
  if($brand==='google_meet')check($last[0]==='https://meet.googleapis.com/v2/spaces'&&$last[1]===['config'=>['accessType'=>'RESTRICTED']],'Meet used invented Calendar fields');
  if($brand==='zoom')check($last[1]['type']===2&&$last[1]['settings']['waiting_room']===true,'Zoom contract');
  if($brand==='webex')check(array_keys($last[1])===['title','start','end'],'Webex contract');
 }
 $meeting['provider']='google_meet';$meeting['google_access_token']='fixture-token';$provider->reply=['status'=>200,'error'=>0,'body'=>json_encode(['name'=>'spaces/a','meetingUri'=>'https://attacker.example/meeting'])];rejects(fn()=>$provider->meeting($meeting,'Fixture',$now+60,30),'unconfirmed');
 $provider->reply=['status'=>200,'error'=>0,'body'=>json_encode(['name'=>'spaces/a','meetingUri'=>'https://meet.google.com/abc-defg-hij'])];
 $incident=['id'=>'inc_'.str_repeat('a',32),'title'=>'Fixture incident','state'=>'open'];$request=str_repeat('a',32);$input=['request_id'=>$request,'start_at'=>$now+60,'duration_minutes'=>30];$calls=count($provider->calls);$claimedTime=null;
 $effect=static function(callable $send,int $created)use(&$claimedTime){$claimedTime=$created;return $send();};
 $result=$service->meeting($meeting,$incident,$input,$effect);$clock+=1;$again=$service->meeting($meeting,$incident,$input,$effect);check($again===$result&&count($provider->calls)===$calls+1&&$claimedTime===$now,'Meeting replay resubmitted/unstable timestamp');
 rejects(fn()=>$service->meeting($meeting,$incident,array_replace($input,['duration_minutes'=>31])),'different');
 rejects(fn()=>$service->meeting($config['meetings'],$incident,$input),'enabled');
 $provider->reply=['status'=>0,'error'=>60,'body'=>''];$uncertain=$service->meeting($meeting,$incident,array_replace($input,['request_id'=>str_repeat('b',32)]));$calls=count($provider->calls);$service->meeting($meeting,$incident,array_replace($input,['request_id'=>str_repeat('b',32)]));check($uncertain['state']==='uncertain'&&count($provider->calls)===$calls,'TLS uncertainty repeated provider operation');
 $door=['id'=>'door_'.str_repeat('c',24),'name'=>'Fixture door','token'=>'Axis-token','allow_read'=>true,'allow_lock'=>true,'allow_unlock'=>false];$access=$config['access_control'];$access=array_replace($access,['enabled'=>'1','origin'=>'https://controller.example.org','pinned_ipv4'=>'192.168.1.5','username'=>'fixture','password'=>'fixture-secret','doors'=>[$door]]);
 $provider->reply=['status'=>200,'error'=>0,'body'=>'{"DoorState":{"DoorMode":"Locked","DoorPhysicalState":"Closed","LockPhysicalState":"Locked","AccountSecret":"hidden"}}'];$observed=$service->door($access,['door_id'=>$door['id'],'operation'=>'read']);check($observed['observed']===['DoorMode'=>'Locked','DoorPhysicalState'=>'Closed','LockPhysicalState'=>'Locked'],'Door telemetry field bounds');$last=$provider->calls[count($provider->calls)-1];check($last[0]==='https://controller.example.org/vapix/doorcontrol'&&$last[1]===['tdc:GetDoorState'=>['Token'=>'Axis-token']],'Door API contract');
 $calls=count($provider->calls);rejects(fn()=>$service->door($access,['request_id'=>str_repeat('d',32),'door_id'=>$door['id'],'operation'=>'unlock']),'permission');check(count($provider->calls)===$calls,'Unpermitted door request');
 $provider->reply=['status'=>200,'error'=>0,'body'=>'{}'];$service->door($access,['request_id'=>str_repeat('d',32),'door_id'=>$door['id'],'operation'=>'lock']);$last=$provider->calls[count($provider->calls)-1];check($last[1]===['tdc:LockDoor'=>['Token'=>'Axis-token']],'Door lock contract');
 $speaker=['id'=>'spk_'.str_repeat('e',24),'enabled'=>'1','brand'=>'axis','telemetry_origin'=>'https://speaker.example.org','telemetry_ipv4'=>'192.168.1.6','telemetry_username'=>'fixture','telemetry_password'=>'fixture'];$provider->reply=['status'=>200,'error'=>0,'body'=>'{"SpeakerTestReport":{"SpeakerTestStatus":"OK","TestTimestamp":"2026-10-01T00:00:00Z","CalibrationTimestamp":""}}'];$receipt=$provider->speakerTelemetry($speaker);$last=$provider->calls[count($provider->calls)-1];check($last[1]===['axast:GetSpeakerTestReport'=>[]]&&str_contains($receipt['detail'],'does not confirm'),'Telemetry started a test or inferred hearing');
 $responses=$config['responses'];$responses['enabled']='1';$person=['id'=>'person_a','name'=>'Fixture person'];$target=['id'=>'sms_'.str_repeat('1',24),'number'=>'+15555550102','provider'=>'twilio'];$binding=$service->bindResponse($responses,$incident,$person,'sms',$target,'fixture-route');$recorded=[];$respond=static function($id,$input,$actor)use(&$recorded){$recorded[]=[$id,$input,$actor];};$current=static fn($row)=>true;
 $event=['inbound'=>true,'opt_out'=>false,'body'=>'SLS '.$binding['token'].' SAFE','event_id'=>'SMfixture1','provider'=>'twilio','from'=>$target['number']];check($service->smsResponse($responses,$event,$current,$respond)['state']==='recorded','SMS human reply not recorded');check($recorded[0][1]['person_id']==='person_a'&&$recorded[0][1]['response']==='safe'&&$recorded[0][2]['source']==='verified_sms_human','SMS response binding');check($service->smsResponse($responses,$event,$current,$respond)['state']==='duplicate'&&count($recorded)===1,'SMS callback replay');
 rejects(fn()=>$service->smsResponse($responses,array_replace($event,['body'=>'SLS '.$binding['token'].' HELP']),$current,$respond),'different');rejects(fn()=>$service->smsResponse($responses,array_replace($event,['provider'=>'telnyx']),$current,$respond),'unique');rejects(fn()=>$service->smsResponse($responses,array_replace($event,['from'=>'+15555550103']),$current,$respond),'unique');check($service->smsResponse($responses,array_replace($event,['body'=>'SAFE']),$current,$respond)['state']==='ignored','Ambiguous plain reply accepted');rejects(fn()=>$service->smsResponse($responses,array_replace($event,['event_id'=>'SMfixture2']),static fn($r)=>false,$respond),'unique');
 $store->transaction(static function(array &$state)use($binding):void { $other=$binding;$other['id']=str_repeat('9',64);$state['bindings'][$other['id']]=$other; });
 rejects(fn()=>$service->smsResponse($responses,array_replace($event,['event_id'=>'SMambiguous']),$current,$respond),'unique');
 $store->transaction(static function(array &$state):void { unset($state['bindings'][str_repeat('9',64)]); });
 $voice=$service->bindResponse($responses,$incident,$person,'voice',['id'=>'voice_'.str_repeat('2',24),'number'=>'+15555550102'],'voice-route');$key=['binding_id'=>$voice['id'],'token'=>$voice['token'],'recipient_id'=>$voice['recipient_id'],'event_id'=>'pbx_fixture1','digit'=>''];check($service->voiceResponse($responses,$key,$current,$respond)['state']==='ignored','Call answer counted as human response');check($service->voiceResponse($responses,array_replace($key,['digit'=>'1']),$current,$respond)['response']==='received','DTMF received');rejects(fn()=>$service->voiceResponse($responses,array_replace($key,['token'=>'BAD','digit'=>'1']),$current,$respond),'binding');
 $rule=['id'=>'trg_'.str_repeat('3',24),'kind'=>'sensor','enabled'=>true];$sensor=['enabled'=>'1'];$heartbeat=['operation'=>'heartbeat','request_id'=>str_repeat('e',32),'sent_at'=>$clock,'expires_at'=>$clock+60,'is_test'=>true];$h=$service->heartbeat($sensor,$rule,$heartbeat);$clock++;check($service->heartbeat($sensor,$rule,$heartbeat)['last_seen']===$h['last_seen'],'Heartbeat replay renewed health');rejects(fn()=>$service->heartbeat($sensor,$rule,array_replace($heartbeat,['request_id'=>str_repeat('f',32)])),'replayed');rejects(fn()=>$service->heartbeat(['enabled'=>'0'],$rule,$heartbeat),'disabled');
 $warning=['identifier'=>'fixture-warning','sender'=>'fixture@example.org','sent'=>gmdate('Y-m-d\TH:i:s\Z',$now),'expires'=>gmdate('Y-m-d\TH:i:s\Z',$now+3600),'event'=>'Fixture exercise','headline'=>'Fixture <headline>','description'=>'Fixture only & no transmission','area_description'=>'Fixture triangle','polygon'=>'40,-90 41,-90 40,-89 40,-90'];$draft=Cap::author($warning,$now);check(str_contains($draft['xml'],'Fixture &lt;headline&gt;')&&$draft['status']==='Test','CAP escaping/default Test');rejects(fn()=>Cap::author(array_replace($warning,['polygon'=>'40,-90 41,-90 40,-89']),$now),'closing');rejects(fn()=>Cap::author(array_replace($warning,['msg_type'=>'Cancel']),$now),'references');
 $private=openssl_pkey_new(['private_key_type'=>OPENSSL_KEYTYPE_RSA,'private_key_bits'=>2048]);$csr=openssl_csr_new(['commonName'=>'IPAWSOPENCOG123'], $private,['digest_alg'=>'sha256']);$cert=openssl_csr_sign($csr,null,$private,1,['digest_alg'=>'sha256']);openssl_x509_export($cert,$pem);openssl_pkey_export($private,$keyPem);$authority=['cog_id'=>'123','logon_user'=>'fixture','certificate_pem'=>$pem,'private_key_pem'=>$keyPem,'private_key_password'=>''];
 $now=time();$signed=Cap::signCap($draft['xml'],$authority,$now);$doc=new DOMDocument();$doc->loadXML($signed);$xpath=new DOMXPath($doc);$xpath->registerNamespace('d','http://www.w3.org/2000/09/xmldsig#');$info=$xpath->query('//d:SignedInfo')->item(0);$sig=base64_decode($xpath->evaluate('string(//d:SignatureValue)'));check(openssl_verify($info->C14N(true,false),$sig,$cert,OPENSSL_ALGO_SHA256)===1,'CAP signature verification');
 $envelope=Cap::acknowledgementEnvelope($authority,$now);$soap=new DOMDocument();$soap->loadXML($envelope);$xp=new DOMXPath($soap);$xp->registerNamespace('s','http://schemas.xmlsoap.org/soap/envelope/');$xp->registerNamespace('d','http://www.w3.org/2000/09/xmldsig#');$xp->registerNamespace('w','http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd');$body=$xp->query('/s:Envelope/s:Body')->item(0);while($body->firstChild)$body->removeChild($body->firstChild);$body->appendChild($soap->importNode($doc->documentElement,true));$security=$xp->query('/s:Envelope/s:Header/w:Security')->item(0);$security->removeChild($xp->query('./d:Signature',$security)->item(0));$method=new ReflectionMethod(Cap::class,'signature');$der=preg_replace('/-----[^-]+-----|\s/','',$pem);$method->invoke(null,$body,$security,'#body',$private,$der,false);$prepared=$soap->saveXML();Cap::verifyPreparedEnvelope($prepared,$draft['xml'],$authority,$now);
 rejects(fn()=>Cap::verifyPreparedEnvelope(str_replace('Fixture &lt;headline&gt;','Changed headline',$prepared),$draft['xml'],$authority,$now),'invalid');rejects(fn()=>Cap::verifyPreparedEnvelope($prepared,Cap::author(array_replace($warning,['headline'=>'Changed']),$now)['xml'],$authority,$now),'differs');rejects(fn()=>Cap::verifyPreparedEnvelope($prepared,$draft['xml'],array_replace($authority,['cog_id'=>'999']),$now),'COG');
 // A malformed durable journal must be preserved, never treated as fresh state.
 unlink($directory.'/worker-state.json');rejects(fn()=>$store->read(),'missing');file_put_contents($directory.'/worker-state.json','{}');rejects(fn()=>$store->read(),'schema');
 echo "Enterprise integration fixtures passed: provider wire contracts, disabled gates, replay, TLS uncertainty, human bindings, heartbeat and signed CAP/SOAP.\n";
} finally {
 foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($temporary,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST) as $file){$file->isDir()&&!$file->isLink()?rmdir($file->getPathname()):unlink($file->getPathname());}
 rmdir($temporary);
}
